version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=5000
      - DB_URL=mongodb://db:27017/mydb
      - JWT_SECRET=${JWT_SECRET}
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
